<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\ApiServiceProvider::class,
    App\Providers\AclServiceProvider::class,
    App\Providers\AssetsServiceProvider::class,
    App\Providers\BaseCommandServiceProvider::class,
    App\Providers\BaseComposerServiceProvider::class,
    App\Providers\BaseEventServiceProvider::class,
    App\Providers\BaseFormServiceProvider::class,
    App\Providers\BaseMailConfigServiceProvider::class,
    App\Providers\BaseServiceProvider::class,
    App\Providers\DataSynchronizeServiceProvider::class,
    App\Providers\DashboardServiceProvider::class,
    App\Providers\GetStartedServiceProvider::class,
    App\Providers\InstallerServiceProvider::class,
    App\Providers\MenuServiceProvider::class,
    App\Providers\MediaServiceProvider::class,
    App\Providers\OptimizeServiceProvider::class,
    App\Providers\PageServiceProvider::class,
    App\Providers\PluginManagementServiceProvider::class,
    App\Providers\RevisionServiceProvider::class,
    App\Providers\SeoHelperServiceProvider::class,
    App\Providers\ShortcodeServiceProvider::class,
    App\Providers\SitemapServiceProvider::class,
    App\Providers\SlugServiceProvider::class,
    App\Providers\SupportServiceProvider::class,
    App\Providers\TableServiceProvider::class,
    App\Providers\ThemeRouteServiceProvider::class,
    App\Providers\ThemeServiceProvider::class,
    App\Providers\WidgetServiceProvider::class,
    App\Providers\JsValidationServiceProvider::class,
    App\Providers\ChartServiceProvider::class,
    App\Providers\IconServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,

    Kris\LaravelFormBuilder\FormBuilderServiceProvider::class,

];
